error[E0433]: failed to resolve: use of undeclared crate or module `fs`
 --> /tmp/yicoder2b-file_exists-py-rs.rs:5:9
  |
5 |     if !fs::exists(&current) {
  |         ^^ use of undeclared crate or module `fs`
  |
help: consider importing this module
  |
1 + use std::fs;
  |

error[E0433]: failed to resolve: use of undeclared crate or module `fs`
 --> /tmp/yicoder2b-file_exists-py-rs.rs:7:15
  |
7 |         match fs::read_dir(&root) {
  |               ^^ use of undeclared crate or module `fs`
  |
help: consider importing this module
  |
1 + use std::fs;
  |

error[E0433]: failed to resolve: use of undeclared crate or module `fs`
  --> /tmp/yicoder2b-file_exists-py-rs.rs:21:26
   |
21 |         if let Some(_) = fs::read_dir(&current) {
   |                          ^^ use of undeclared crate or module `fs`
   |
help: consider importing this module
   |
1  + use std::fs;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `fs`
  --> /tmp/yicoder2b-file_exists-py-rs.rs:23:32
   |
23 |         } else if let Err(e) = fs::read_dir(&root) {
   |                                ^^ use of undeclared crate or module `fs`
   |
help: consider importing this module
   |
1  + use std::fs;
   |

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0433`.
